export default {
  navEditor: 'المحرر',
  navAnalysis: 'فحص الأمان والـ IDE',
  projectGraph: 'اعتماديات المشروع والتحليل الذكي',
  undo: 'تراجع',
  reset: 'إعادة ضبط',
  systemStatus: 'حالة النظام',
  readyReview: 'جاهز للمراجعة الآمنة',
  smartEditorTitle: 'محرر التعديلات الذكي',
  smartEditorDesc: 'واجهة فاخرة مستوحاة من الأخضر الزمردي والنحاسي — مع فصل واضح بين الملف الأصلي وتعديلات SEARCH / REPLACE.',
  tagline: 'نسخة مميزة • تعديل آمن • تحقق • تراجع',
  compilerLabel: 'المترجم:',
  compilerServerOn: 'سيرفر المترجم: متصل (ON)',
  compilerServerOff: 'سيرفر المترجم: متوقف (OFF)',
  compilerServerOffline: 'سيرفر المترجم غير متاح حالياً. شغّل "npm run server" ثم أعد المحاولة.',
  analyzeProject: 'تحليل المشروع',
  aiPromptButton: 'معلومات الأداة للذكاء الاصطناعي',
  aiPromptCopied: 'تم نسخ البرومت',
  fileNameLabel: 'اسم الملف',
  workspacePathLabel: 'مسار المشروع (project commit)',
  fileTypeLabel: 'النوع',
  charsLabel: 'عدد الأحرف',
  originalEditor: 'الملف الأصلي / Editor',
  uploadFile: 'رفع ملف',
  patchSectionTitle: 'تعديلات SEARCH / REPLACE',
  blocksMetric: 'الكتل',
  errorsMetric: 'الأخطاء',
  addFiles: 'إضافة ملف',
  run: 'فحص وتطبيق كل التعديلات بأمان',
  running: 'جاري تشغيل بوابات المعاملة…',
  reviewApprovedLabel: 'الموافقة على نتائج المراجعة',
  reviewApprovedHint: 'بعض الملاحظات تتطلب إذناً يدوياً للموافقة. راجع التحذيرات ثم علّم هنا للمتابعة.',
  prepareProjectTransaction: 'تجهيز معاملة المشروع',
  commitPreparedProject: 'اعتماد معاملة المشروع',
  result: 'النتيجة المعتمدة',
  copy: 'نسخ',
  copied: 'تم النسخ',
  download: 'تنزيل',
  auditReportSummary: '📋 عرض تقرير التدقيق الفني (JSON Audit Report)',
  loadFirstToAnalyze: 'يرجى تحميل ملف أولاً لتشغيل التحليل.',
  staticIntelligenceTitle: 'التحليل الذكي للكود (Static Intelligence)',
  diagnosticsMetric: 'التشخيصات',
  taintSources: 'مصادر Taint',
  taintSinks: 'أهداف Taint',
  taintMetric: 'تدفقات Taint',
  filesMetric: 'الملفات',
  cyclesMetric: 'الدورات المغلقة',
  typeConsistencyTitle: 'تشخيصات النوع والاتساق',
  noTypeDiagnostics: 'لا توجد مشاكل في النوع أو الاتساق.',
  taintFlowTitle: 'تدفق البيانات / Taint',
  noTaintFlows: 'لم يتم رصد أي تدفق بيانات بالقواعد الحالية.',
  intelligenceNote: 'هذه فحوصات تحليل ثابت؛ لا يتم تشغيل الكود مطلقاً.',
  line: 'سطر',
  sourceLabel: 'مصدر',
  targetLabel: 'هدف',
  emptyCode: 'الكود الأصلي فارغ.',
  invalidPatch: 'الـPatch غير صالح. يرجى تصحيح الأخطاء أولاً.',
  tx: 'معاملة جارية: التحقق ← التطبيق ← الفحص الأمني ← السلامة',
  successServerMsg: 'V23: تم اجتياز بوابات المترجم على السيرفر + محرك الباتش + AST + الأمان + سلامة البيانات.',
  successWorkerMsg: 'V23: تم اجتياز بوابات محرك الباتش + AST + الأمان + سلامة البيانات.',
  rejectedFallbackMsg: 'تم رفض المعاملة والتراجع عن كل التعديلات (Rollback).',
  executionFailureMsg: 'فشل التنفيذ',
  projectServerErrorMsg: 'خطأ في سيرفر المشروع.',
  projectCommitErrorMsg: 'خطأ في اعتماد معاملة المشروع.',
  secEvalTitle: '⚠️ تنبيه أمني عالي الخطورة',
  secEvalDesc: 'تم رفض الكود لاحتوائه على أمر تنفيذ ديناميكي (eval/exec) يتيح تشغيل شفرات غير موثوقة قد تعرض نظامك للخطر.',
  secSecretTitle: '🔑 تنبيه تسريب مفتاح سري',
  secSecretDesc: 'تم اكتشاف مفتاح API أو كلمة سر مكتوبة بشكل مكشوف داخل الكود. يُنصح بنقلها إلى ملفات .env.',
  secXssTitle: '⚠️ تحذير أمان الواجهة (XSS)',
  secXssDesc: 'تم اكتشاف تعديل مباشر لـ innerHTML قد يفتح ثغرة حقن خبيثة إذا كانت المدخلات غير معقمة.',
  secSafeTitle: '✓ الكود آمن ومعتمد',
  secSafeDesc: 'تم اجتياز جميع فحوصات القواعد وبوابات السلامة النحوية والأمنية بنجاح.',
  secGenericTitle: '⚠️ تنبيه أمني',
  secGenericDesc: 'تم رصد ملاحظات أمنية أو بنيوية تتطلب المراجعة قبل الاعتماد.'
};
