export default {
  navEditor: 'Editor',
  navAnalysis: 'Security & IDE',
  projectGraph: 'Project Graph & Intelligence',
  undo: 'Undo',
  reset: 'Reset',
  systemStatus: 'System status',
  readyReview: 'Ready for safe review',
  smartEditorTitle: 'Smart Patch Editor',
  smartEditorDesc: 'Luxury workspace with clear separation between original files and SEARCH / REPLACE patches.',
  tagline: 'Premium • Safe Patch • Verify • Rollback',
  compilerLabel: 'Compiler:',
  compilerServerOn: 'Compiler Server: ON',
  compilerServerOff: 'Compiler Server: OFF',
  compilerServerOffline: 'Compiler Server is offline. Run "npm run server" then retry.',
  analyzeProject: 'Analyze project',
  aiPromptButton: 'AI tool info',
  aiPromptCopied: 'Prompt copied',
  fileNameLabel: 'File name',
  workspacePathLabel: 'Workspace path (project commit)',
  fileTypeLabel: 'Type',
  charsLabel: 'Chars',
  originalEditor: 'Original / Editor',
  uploadFile: 'Upload file',
  patchSectionTitle: 'SEARCH / REPLACE Patch',
  blocksMetric: 'Blocks',
  errorsMetric: 'Errors',
  addFiles: 'Add file',
  run: 'Safely validate and apply all changes',
  running: 'Running transaction gates…',
  reviewApprovedLabel: 'Approve pending review findings',
  reviewApprovedHint: 'Some findings require human approval. Check this box and retry to proceed.',
  prepareProjectTransaction: 'Prepare project transaction',
  commitPreparedProject: 'Commit prepared project',
  result: 'Approved Result',
  copy: 'Copy',
  copied: 'Copied',
  download: 'Download',
  auditReportSummary: '📋 View technical audit report (JSON Audit Report)',
  loadFirstToAnalyze: 'Load a file first to run analysis.',
  staticIntelligenceTitle: 'Static Intelligence',
  diagnosticsMetric: 'Diagnostics',
  taintSources: 'Taint sources',
  taintSinks: 'Taint sinks',
  taintMetric: 'Taint flows',
  filesMetric: 'Files',
  cyclesMetric: 'Cycles',
  typeConsistencyTitle: 'Type / consistency diagnostics',
  noTypeDiagnostics: 'No static type/consistency diagnostics.',
  taintFlowTitle: 'Data-flow / taint',
  noTaintFlows: 'No source-to-sink flow detected by current rules.',
  intelligenceNote: 'Static analysis only; code is never executed.',
  line: 'line',
  sourceLabel: 'source',
  targetLabel: 'target',
  emptyCode: 'Original code is empty.',
  invalidPatch: 'Invalid Patch. Fix all errors first.',
  tx: 'Transaction: Parse → Preflight → Apply → Verify → Replay → Validate → Audit → Integrity → Commit',
  successServerMsg: 'V23: Server Compiler + Patch Core + AST + Security + Integrity gates passed.',
  successWorkerMsg: 'V23: Patch Core + AST + Security + Integrity gates passed.',
  rejectedFallbackMsg: 'Transaction rejected and rolled back.',
  executionFailureMsg: 'Execution failure',
  projectServerErrorMsg: 'Project server error.',
  projectCommitErrorMsg: 'Project commit error.',
  secEvalTitle: '⚠️ Critical Security Alert',
  secEvalDesc: 'Dynamic execution command (eval/exec) detected. Untrusted code puts your system at risk.',
  secSecretTitle: '🔑 Hardcoded Secret Warning',
  secSecretDesc: 'API key or credential exposed in code. Move sensitive credentials to .env files.',
  secXssTitle: '⚠️ Interface Security Warning (XSS)',
  secXssDesc: 'Direct innerHTML modification detected; risk of Cross-Site Scripting (XSS).',
  secSafeTitle: '✓ Code Verified & Safe',
  secSafeDesc: 'All syntax gates, AST rules, and security checks passed successfully.',
  secGenericTitle: '⚠️ Security Alert',
  secGenericDesc: 'Structural or security findings detected that require review before commit.'
};
